/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user.dialog;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author USER
 */
public class dialogFrame_Pembayaran_sukses extends javax.swing.JFrame {

    /**
     * Creates new form dialogFrame_Pembayaran_sukses
     */
    public dialogFrame_Pembayaran_sukses() {
        initComponents();
        
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnContinue = new javax.swing.JButton();
        label_pembayaran_berhasil = new javax.swing.JLabel();
        icon_sukses = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnContinue.setBackground(new java.awt.Color(47, 54, 64));
        btnContinue.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        btnContinue.setForeground(new java.awt.Color(255, 255, 255));
        btnContinue.setText("Continue");
        btnContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContinueMouseClicked(evt);
            }
        });
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 120, 40));

        label_pembayaran_berhasil.setBackground(new java.awt.Color(48, 57, 82));
        label_pembayaran_berhasil.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 18)); // NOI18N
        label_pembayaran_berhasil.setForeground(new java.awt.Color(48, 57, 82));
        label_pembayaran_berhasil.setText("Pembayaran Berhasil !");
        getContentPane().add(label_pembayaran_berhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, 30));

        icon_sukses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_sukses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/img/ceklis.gif"))); // NOI18N
        getContentPane().add(icon_sukses, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 100, 90));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/img/BackgroundDialog.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 400, 250));

        setSize(new java.awt.Dimension(606, 365));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueMouseClicked
        // TODO add your handling code here:

        //        this.setVisible(false);
    }//GEN-LAST:event_btnContinueMouseClicked

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);

    }//GEN-LAST:event_btnContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogFrame_Pembayaran_sukses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogFrame_Pembayaran_sukses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogFrame_Pembayaran_sukses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogFrame_Pembayaran_sukses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dialogFrame_Pembayaran_sukses().setVisible(true);
            }
        });
    }

    public JButton getBtnContinue() {
        return btnContinue;
    }

    public void setBtnContinue(JButton btnContinue) {
        this.btnContinue = btnContinue;
    }

    public void addListener(MouseListener mouseListener) {
        btnContinue.addMouseListener(mouseListener);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnContinue;
    private javax.swing.JLabel icon_sukses;
    private javax.swing.JLabel label_pembayaran_berhasil;
    // End of variables declaration//GEN-END:variables
}
