/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.kasir.menu;

import view.user.*;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class Kasir_Transaksi_Selesai_LihatTiket extends javax.swing.JFrame {

    /**
     * Creates new form View_Panel_User_ListPenerbangan
     */
    public Kasir_Transaksi_Selesai_LihatTiket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        moveableFrame1 = new javax.swing.JPanel();
        txt_keberangkatan2 = new javax.swing.JLabel();
        txt_tujuan2 = new javax.swing.JLabel();
        txt_asal2 = new javax.swing.JLabel();
        txt_jumlahKursi2 = new javax.swing.JLabel();
        txt_namaPemesan2 = new javax.swing.JLabel();
        txt_kelasPenerbangan = new javax.swing.JLabel();
        txt_keberangkatan = new javax.swing.JLabel();
        txt_jumlahKursi = new javax.swing.JLabel();
        txt_namaPemesan = new javax.swing.JLabel();
        txt_tujuan = new javax.swing.JLabel();
        txt_asal = new javax.swing.JLabel();
        TiketImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(48, 57, 82));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(153, 153, 153));
        Background.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/img/btnBack2.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        Background.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 40, 40));

        moveableFrame1.setOpaque(false);
        moveableFrame1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveableFrame1MouseDragged(evt);
            }
        });
        moveableFrame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveableFrame1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout moveableFrame1Layout = new javax.swing.GroupLayout(moveableFrame1);
        moveableFrame1.setLayout(moveableFrame1Layout);
        moveableFrame1Layout.setHorizontalGroup(
            moveableFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        moveableFrame1Layout.setVerticalGroup(
            moveableFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Background.add(moveableFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 40));

        txt_keberangkatan2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txt_keberangkatan2.setForeground(new java.awt.Color(0, 0, 0));
        txt_keberangkatan2.setText("Joe Taslim");
        Background.add(txt_keberangkatan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, -1));

        txt_tujuan2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txt_tujuan2.setForeground(new java.awt.Color(0, 0, 0));
        txt_tujuan2.setText("Joe Taslim");
        Background.add(txt_tujuan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        txt_asal2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txt_asal2.setForeground(new java.awt.Color(0, 0, 0));
        txt_asal2.setText("Joe Taslim");
        Background.add(txt_asal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, -1, -1));

        txt_jumlahKursi2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txt_jumlahKursi2.setForeground(new java.awt.Color(0, 0, 0));
        txt_jumlahKursi2.setText("Joe Taslim");
        Background.add(txt_jumlahKursi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));

        txt_namaPemesan2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txt_namaPemesan2.setForeground(new java.awt.Color(0, 0, 0));
        txt_namaPemesan2.setText("Joe Taslim");
        Background.add(txt_namaPemesan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, -1, -1));

        txt_kelasPenerbangan.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txt_kelasPenerbangan.setForeground(new java.awt.Color(0, 0, 0));
        txt_kelasPenerbangan.setText("Joe Taslim");
        Background.add(txt_kelasPenerbangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        txt_keberangkatan.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txt_keberangkatan.setForeground(new java.awt.Color(0, 0, 0));
        txt_keberangkatan.setText("Joe Taslim");
        Background.add(txt_keberangkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        txt_jumlahKursi.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txt_jumlahKursi.setForeground(new java.awt.Color(0, 0, 0));
        txt_jumlahKursi.setText("Joe Taslim");
        Background.add(txt_jumlahKursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        txt_namaPemesan.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txt_namaPemesan.setForeground(new java.awt.Color(0, 0, 0));
        txt_namaPemesan.setText("Joe Taslim");
        Background.add(txt_namaPemesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        txt_tujuan.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txt_tujuan.setForeground(new java.awt.Color(0, 0, 0));
        txt_tujuan.setText("Joe Taslim");
        Background.add(txt_tujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        txt_asal.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txt_asal.setForeground(new java.awt.Color(0, 0, 0));
        txt_asal.setText("Joe Taslim");
        Background.add(txt_asal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        TiketImage.setBackground(new java.awt.Color(48, 57, 82));
        TiketImage.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        TiketImage.setForeground(new java.awt.Color(48, 57, 82));
        TiketImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/img/Tiket.png"))); // NOI18N
        TiketImage.setBorder(new javax.swing.border.MatteBorder(null));
        Background.add(TiketImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, 260));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void moveableFrame1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveableFrame1MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse ,y-yMouse);
    }//GEN-LAST:event_moveableFrame1MouseDragged

    private void moveableFrame1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveableFrame1MousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_moveableFrame1MousePressed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked

    }//GEN-LAST:event_btnBackMouseClicked

    private int xMouse, yMouse;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir_Transaksi_Selesai_LihatTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir_Transaksi_Selesai_LihatTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir_Transaksi_Selesai_LihatTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir_Transaksi_Selesai_LihatTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir_Transaksi_Selesai_LihatTiket().setVisible(true);
            }
        });
    }

    public JLabel getBtnBack() {
        return btnBack;
    }

    public void setBtnBack(JLabel btnBack) {
        this.btnBack = btnBack;
    }

    public JLabel getTxt_asal() {
        return txt_asal;
    }

    public void setTxt_asal(JLabel txt_asal) {
        this.txt_asal = txt_asal;
    }

    public JLabel getTxt_asal2() {
        return txt_asal2;
    }

    public void setTxt_asal2(JLabel txt_asal2) {
        this.txt_asal2 = txt_asal2;
    }

    public JLabel getTxt_jumlahKursi() {
        return txt_jumlahKursi;
    }

    public void setTxt_jumlahKursi(JLabel txt_jumlahKursi) {
        this.txt_jumlahKursi = txt_jumlahKursi;
    }

    public JLabel getTxt_jumlahKursi2() {
        return txt_jumlahKursi2;
    }

    public void setTxt_jumlahKursi2(JLabel txt_jumlahKursi2) {
        this.txt_jumlahKursi2 = txt_jumlahKursi2;
    }

    public JLabel getTxt_keberangkatan() {
        return txt_keberangkatan;
    }

    public void setTxt_keberangkatan(JLabel txt_keberangkatan) {
        this.txt_keberangkatan = txt_keberangkatan;
    }

    public JLabel getTxt_keberangkatan2() {
        return txt_keberangkatan2;
    }

    public void setTxt_keberangkatan2(JLabel txt_keberangkatan2) {
        this.txt_keberangkatan2 = txt_keberangkatan2;
    }

    public JLabel getTxt_kelasPenerbangan() {
        return txt_kelasPenerbangan;
    }

    public void setTxt_kelasPenerbangan(JLabel txt_kelasPenerbangan) {
        this.txt_kelasPenerbangan = txt_kelasPenerbangan;
    }

    public JLabel getTxt_namaPemesan() {
        return txt_namaPemesan;
    }

    public void setTxt_namaPemesan(JLabel txt_namaPemesan) {
        this.txt_namaPemesan = txt_namaPemesan;
    }

    public JLabel getTxt_namaPemesan2() {
        return txt_namaPemesan2;
    }

    public void setTxt_namaPemesan2(JLabel txt_namaPemesan2) {
        this.txt_namaPemesan2 = txt_namaPemesan2;
    }

    public JLabel getTxt_tujuan() {
        return txt_tujuan;
    }

    public void setTxt_tujuan(JLabel txt_tujuan) {
        this.txt_tujuan = txt_tujuan;
    }

    public JLabel getTxt_tujuan2() {
        return txt_tujuan2;
    }

    public void setTxt_tujuan2(JLabel txt_tujuan2) {
        this.txt_tujuan2 = txt_tujuan2;
    }

    public void addListener(MouseListener mouseListener) {
       btnBack.addMouseListener(mouseListener);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel TiketImage;
    private javax.swing.JLabel btnBack;
    private javax.swing.JPanel moveableFrame1;
    private javax.swing.JLabel txt_asal;
    private javax.swing.JLabel txt_asal2;
    private javax.swing.JLabel txt_jumlahKursi;
    private javax.swing.JLabel txt_jumlahKursi2;
    private javax.swing.JLabel txt_keberangkatan;
    private javax.swing.JLabel txt_keberangkatan2;
    private javax.swing.JLabel txt_kelasPenerbangan;
    private javax.swing.JLabel txt_namaPemesan;
    private javax.swing.JLabel txt_namaPemesan2;
    private javax.swing.JLabel txt_tujuan;
    private javax.swing.JLabel txt_tujuan2;
    // End of variables declaration//GEN-END:variables
}
