/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user;

import java.awt.event.MouseListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import tabel.TabelBookingModel;
import view.admin.menu.Admin_Atur_Data_Bandara;

/**
 *
 * @author USER
 */
public class View_Panel_User_Menu_Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form View_Panel_User_ListPenerbangan
     */
    public View_Panel_User_Menu_Transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_List_Penerbangan = new javax.swing.JPanel();
        btnBack2 = new javax.swing.JLabel();
        moveableFrame1 = new javax.swing.JPanel();
        borderList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLihatTiket = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_id_booking = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_nama_penumpang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_nomor_hp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_jumlah_penumpang = new javax.swing.JTextField();
        Background = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(48, 57, 82));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_List_Penerbangan.setBackground(new java.awt.Color(255, 255, 255));
        Panel_List_Penerbangan.setForeground(new java.awt.Color(255, 255, 255));
        Panel_List_Penerbangan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/img/btnBack2.png"))); // NOI18N
        btnBack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBack2MouseClicked(evt);
            }
        });
        Panel_List_Penerbangan.add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 40, 40));

        moveableFrame1.setOpaque(false);
        moveableFrame1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveableFrame1MouseDragged(evt);
            }
        });
        moveableFrame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveableFrame1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout moveableFrame1Layout = new javax.swing.GroupLayout(moveableFrame1);
        moveableFrame1.setLayout(moveableFrame1Layout);
        moveableFrame1Layout.setHorizontalGroup(
            moveableFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        moveableFrame1Layout.setVerticalGroup(
            moveableFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel_List_Penerbangan.add(moveableFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 40));

        borderList.setBackground(new java.awt.Color(48, 57, 82));
        borderList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(48, 57, 82));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Booking", "Nama Pemesan", "Nomor HP", "Jumlah Penumpang"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        borderList.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 480, 290));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("List Booking");
        borderList.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        Panel_List_Penerbangan.add(borderList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 500, 350));

        jLabel11.setBackground(new java.awt.Color(48, 57, 82));
        jLabel11.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(48, 57, 82));
        jLabel11.setText("Daftar Transaksi");
        Panel_List_Penerbangan.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel7.setBackground(new java.awt.Color(48, 57, 82));
        jLabel7.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(48, 57, 82));
        jLabel7.setText("Detail Booking");
        Panel_List_Penerbangan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        btnLihatTiket.setBackground(new java.awt.Color(47, 54, 64));
        btnLihatTiket.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        btnLihatTiket.setForeground(new java.awt.Color(255, 255, 255));
        btnLihatTiket.setText("Lihat Tiket");
        btnLihatTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLihatTiketMouseClicked(evt);
            }
        });
        btnLihatTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatTiketActionPerformed(evt);
            }
        });
        Panel_List_Penerbangan.add(btnLihatTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 180, 50));

        jLabel8.setBackground(new java.awt.Color(48, 57, 82));
        jLabel8.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(48, 57, 82));
        jLabel8.setText("ID Booking");
        Panel_List_Penerbangan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        txt_id_booking.setForeground(new java.awt.Color(0, 0, 0));
        txt_id_booking.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_id_booking.setEnabled(false);
        txt_id_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_bookingActionPerformed(evt);
            }
        });
        Panel_List_Penerbangan.add(txt_id_booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 180, 30));

        jLabel9.setBackground(new java.awt.Color(48, 57, 82));
        jLabel9.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(48, 57, 82));
        jLabel9.setText("Nama Penumpang");
        Panel_List_Penerbangan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        txt_nama_penumpang.setForeground(new java.awt.Color(0, 0, 0));
        txt_nama_penumpang.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nama_penumpang.setEnabled(false);
        txt_nama_penumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_penumpangActionPerformed(evt);
            }
        });
        Panel_List_Penerbangan.add(txt_nama_penumpang, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 180, 30));

        jLabel10.setBackground(new java.awt.Color(48, 57, 82));
        jLabel10.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(48, 57, 82));
        jLabel10.setText("Nomor HP");
        Panel_List_Penerbangan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        txt_nomor_hp.setForeground(new java.awt.Color(0, 0, 0));
        txt_nomor_hp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nomor_hp.setEnabled(false);
        txt_nomor_hp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomor_hpActionPerformed(evt);
            }
        });
        Panel_List_Penerbangan.add(txt_nomor_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 180, 30));

        jLabel6.setBackground(new java.awt.Color(48, 57, 82));
        jLabel6.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(48, 57, 82));
        jLabel6.setText("Jumlah Penumpang");
        Panel_List_Penerbangan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        txt_jumlah_penumpang.setForeground(new java.awt.Color(0, 0, 0));
        txt_jumlah_penumpang.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_jumlah_penumpang.setEnabled(false);
        txt_jumlah_penumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlah_penumpangActionPerformed(evt);
            }
        });
        Panel_List_Penerbangan.add(txt_jumlah_penumpang, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 180, 30));

        getContentPane().add(Panel_List_Penerbangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 580));

        Background.setBackground(new java.awt.Color(48, 57, 82));
        Background.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLihatTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatTiketActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnLihatTiketActionPerformed

    private void btnLihatTiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLihatTiketMouseClicked
        // TODO add your handling code here:

        //        this.setVisible(false);
    }//GEN-LAST:event_btnLihatTiketMouseClicked

    private void moveableFrame1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveableFrame1MousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_moveableFrame1MousePressed

    private void moveableFrame1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveableFrame1MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse ,y-yMouse);
    }//GEN-LAST:event_moveableFrame1MouseDragged

    private void btnBack2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack2MouseClicked

    }//GEN-LAST:event_btnBack2MouseClicked

    private void txt_id_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_bookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_bookingActionPerformed

    private void txt_nama_penumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_penumpangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_penumpangActionPerformed

    private void txt_nomor_hpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomor_hpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomor_hpActionPerformed

    private void txt_jumlah_penumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlah_penumpangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlah_penumpangActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        setDataField();
    }//GEN-LAST:event_jTable1MouseClicked

    private int xMouse, yMouse;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Panel_User_Menu_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Panel_User_Menu_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Panel_User_Menu_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Panel_User_Menu_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Panel_User_Menu_Transaksi().setVisible(true);
            }
        });
    }

    public JButton getBtnLihatTiket() {
        return btnLihatTiket;
    }

    public void setBtnLihatTiket(JButton btnPilihPenerbangan) {
        this.btnLihatTiket = btnPilihPenerbangan;
    }

    public JLabel getBtnBack2() {
        return btnBack2;
    }

    public void setBtnBack2(JLabel btnBack2) {
        this.btnBack2 = btnBack2;
    }
    
    public void addListener(MouseListener mouseListener) {
        btnLihatTiket.addMouseListener(mouseListener);
        btnBack2.addMouseListener(mouseListener);
    }

    public JTextField getTxt_id_booking() {
        return txt_id_booking;
    }

    public void setTxt_id_booking(JTextField txt_id_booking) {
        this.txt_id_booking = txt_id_booking;
    }

    public JTextField getTxt_jumlah_penumpang() {
        return txt_jumlah_penumpang;
    }

    public void setTxt_jumlah_penumpang(JTextField txt_jumlah_penumpang) {
        this.txt_jumlah_penumpang = txt_jumlah_penumpang;
    }

    public JTextField getTxt_nama_penumpang() {
        return txt_nama_penumpang;
    }

    public void setTxt_nama_penumpang(JTextField txt_nama_penumpang) {
        this.txt_nama_penumpang = txt_nama_penumpang;
    }

    public JTextField getTxt_nomor_hp() {
        return txt_nomor_hp;
    }

    public void setTxt_nomor_hp(JTextField txt_nomor_hp) {
        this.txt_nomor_hp = txt_nomor_hp;
    }
      
    
    
    public void clearTextField() {
        txt_id_booking.setText(null);
        txt_nama_penumpang.setText(null);
        txt_jumlah_penumpang.setText(null);
        txt_nomor_hp.setText(null);
    }

    public void fillTabelBooking(TabelBookingModel booking) {
        jTable1.setModel(booking);
    }
    
    public void setDataField(){
        int row;
        row = jTable1.getSelectedRow();
        
        if (row != -1){
            try {
                txt_id_booking.setText((String)jTable1.getModel().getValueAt(row, 0));
                txt_nama_penumpang.setText((String)jTable1.getModel().getValueAt(row, 1));
                txt_nomor_hp.setText((String)jTable1.getModel().getValueAt(row, 2));
                txt_jumlah_penumpang.setText((String)jTable1.getModel().getValueAt(row, 3));
            } catch (SecurityException ex) {
                Logger.getLogger(Admin_Atur_Data_Bandara.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
   }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Panel_List_Penerbangan;
    private javax.swing.JPanel borderList;
    private javax.swing.JLabel btnBack2;
    private javax.swing.JButton btnLihatTiket;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel moveableFrame1;
    private javax.swing.JTextField txt_id_booking;
    private javax.swing.JTextField txt_jumlah_penumpang;
    private javax.swing.JTextField txt_nama_penumpang;
    private javax.swing.JTextField txt_nomor_hp;
    // End of variables declaration//GEN-END:variables
}
