/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author USER
 */
public class View_Panel_User_pilih_Kursi extends javax.swing.JFrame {
    List<JLabel> listkursi = new ArrayList();
    /**
     * Creates new form View_Panel_User_IsiDataPenumpang
     */
    public View_Panel_User_pilih_Kursi() {
  
        initComponents();
        JLabel [] myKursi = {
            kursi1,  kursi2,  kursi3,  kursi4,  kursi5,  kursi6,  kursi7,  kursi8,  kursi9,  kursi10, 
            kursi11, kursi12, kursi13, kursi14, kursi15, kursi16, kursi17, kursi18, kursi19, kursi20, 
            kursi21, kursi22, kursi23, kursi24, kursi25, kursi26, kursi27, kursi28, kursi29, kursi30, 
            kursi31, kursi32, kursi33, kursi34, kursi35, kursi36, kursi37, kursi38, kursi39, kursi40
        };
        
        int [] myArray = {
            0,0,0,0,0,1,0,1,1,0,
            0,0,0,0,0,1,0,1,1,0,
            0,0,0,0,0,1,0,1,1,0,
            0,0,0,0,0,1,0,1,1,0
        };
        for (int i = 0; i < myKursi.length; i++) {
            if (myArray[i] == 0) {
                myKursi[i].setIcon(new ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png")));
            } else if (myArray[i] == 1) {
                myKursi[i].setIcon(new ImageIcon(getClass().getResource("/asset/seat/seatBox_not_available.png")));
            }
        }
        
        for (JLabel kursi : myKursi) {
            kursi.addMouseListener(new MouseAdapter()
            {
                @Override
                public void mouseClicked(MouseEvent e) 
                {
                    if (listkursi.contains(kursi)) {
                        kursi.setIcon(new ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png")));
                        listkursi.remove(kursi);
                    } else {
                        kursi.setIcon(new ImageIcon(getClass().getResource("/asset/seat/seatBox_selected.png")));
                        listkursi.add(kursi);
                    }
                    
                }
            });
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_List_Penerbangan = new javax.swing.JPanel();
        btnBack2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        moveableFrame1 = new javax.swing.JPanel();
        btnSimpanData = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        kursi40 = new javax.swing.JLabel();
        kursi39 = new javax.swing.JLabel();
        kursi38 = new javax.swing.JLabel();
        kursi37 = new javax.swing.JLabel();
        kursi36 = new javax.swing.JLabel();
        kursi35 = new javax.swing.JLabel();
        kursi34 = new javax.swing.JLabel();
        kursi33 = new javax.swing.JLabel();
        kursi32 = new javax.swing.JLabel();
        kursi31 = new javax.swing.JLabel();
        kursi30 = new javax.swing.JLabel();
        kursi29 = new javax.swing.JLabel();
        kursi28 = new javax.swing.JLabel();
        kursi27 = new javax.swing.JLabel();
        kursi26 = new javax.swing.JLabel();
        kursi25 = new javax.swing.JLabel();
        kursi24 = new javax.swing.JLabel();
        kursi23 = new javax.swing.JLabel();
        kursi21 = new javax.swing.JLabel();
        kursi22 = new javax.swing.JLabel();
        kursi20 = new javax.swing.JLabel();
        kursi19 = new javax.swing.JLabel();
        kursi18 = new javax.swing.JLabel();
        kursi17 = new javax.swing.JLabel();
        kursi16 = new javax.swing.JLabel();
        kursi15 = new javax.swing.JLabel();
        kursi14 = new javax.swing.JLabel();
        kursi13 = new javax.swing.JLabel();
        kursi12 = new javax.swing.JLabel();
        kursi11 = new javax.swing.JLabel();
        kursi10 = new javax.swing.JLabel();
        kursi9 = new javax.swing.JLabel();
        kursi8 = new javax.swing.JLabel();
        kursi7 = new javax.swing.JLabel();
        kursi6 = new javax.swing.JLabel();
        kursi5 = new javax.swing.JLabel();
        kursi4 = new javax.swing.JLabel();
        kursi3 = new javax.swing.JLabel();
        kursi2 = new javax.swing.JLabel();
        kursi1 = new javax.swing.JLabel();
        no_2 = new javax.swing.JLabel();
        no_3 = new javax.swing.JLabel();
        no_4 = new javax.swing.JLabel();
        no_5 = new javax.swing.JLabel();
        no_6 = new javax.swing.JLabel();
        no_7 = new javax.swing.JLabel();
        no_8 = new javax.swing.JLabel();
        no_9 = new javax.swing.JLabel();
        no_10 = new javax.swing.JLabel();
        no_1 = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        ex_selected = new javax.swing.JLabel();
        ex_available = new javax.swing.JLabel();
        ex_not_available2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_List_Penerbangan.setBackground(new java.awt.Color(255, 255, 255));
        Panel_List_Penerbangan.setForeground(new java.awt.Color(255, 255, 255));
        Panel_List_Penerbangan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/img/btnBack2.png"))); // NOI18N
        btnBack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBack2MouseClicked(evt);
            }
        });
        Panel_List_Penerbangan.add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 40, 40));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(48, 57, 82));
        jLabel12.setText("Pilihanmu");
        Panel_List_Penerbangan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 130, 40));

        moveableFrame1.setOpaque(false);
        moveableFrame1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveableFrame1MouseDragged(evt);
            }
        });
        moveableFrame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveableFrame1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout moveableFrame1Layout = new javax.swing.GroupLayout(moveableFrame1);
        moveableFrame1.setLayout(moveableFrame1Layout);
        moveableFrame1Layout.setHorizontalGroup(
            moveableFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        moveableFrame1Layout.setVerticalGroup(
            moveableFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Panel_List_Penerbangan.add(moveableFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 40));

        btnSimpanData.setBackground(new java.awt.Color(47, 54, 64));
        btnSimpanData.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        btnSimpanData.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanData.setText("Simpan");
        btnSimpanData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanDataMouseClicked(evt);
            }
        });
        btnSimpanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanDataActionPerformed(evt);
            }
        });
        Panel_List_Penerbangan.add(btnSimpanData, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 180, 50));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kursi40.setBackground(new java.awt.Color(48, 57, 82));
        kursi40.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi40.setForeground(new java.awt.Color(48, 57, 82));
        kursi40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi40.setText("kursi1");
        jPanel1.add(kursi40, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 40, -1));

        kursi39.setBackground(new java.awt.Color(48, 57, 82));
        kursi39.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi39.setForeground(new java.awt.Color(48, 57, 82));
        kursi39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi39.setText("kursi1");
        jPanel1.add(kursi39, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 40, -1));

        kursi38.setBackground(new java.awt.Color(48, 57, 82));
        kursi38.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi38.setForeground(new java.awt.Color(48, 57, 82));
        kursi38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi38.setText("kursi1");
        jPanel1.add(kursi38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 40, -1));

        kursi37.setBackground(new java.awt.Color(48, 57, 82));
        kursi37.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi37.setForeground(new java.awt.Color(48, 57, 82));
        kursi37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi37.setText("kursi1");
        jPanel1.add(kursi37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 40, -1));

        kursi36.setBackground(new java.awt.Color(48, 57, 82));
        kursi36.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi36.setForeground(new java.awt.Color(48, 57, 82));
        kursi36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi36.setText("kursi1");
        jPanel1.add(kursi36, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 40, -1));

        kursi35.setBackground(new java.awt.Color(48, 57, 82));
        kursi35.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi35.setForeground(new java.awt.Color(48, 57, 82));
        kursi35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi35.setText("kursi1");
        jPanel1.add(kursi35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 40, -1));

        kursi34.setBackground(new java.awt.Color(48, 57, 82));
        kursi34.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi34.setForeground(new java.awt.Color(48, 57, 82));
        kursi34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi34.setText("kursi1");
        jPanel1.add(kursi34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 40, -1));

        kursi33.setBackground(new java.awt.Color(48, 57, 82));
        kursi33.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi33.setForeground(new java.awt.Color(48, 57, 82));
        kursi33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi33.setText("kursi1");
        jPanel1.add(kursi33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 40, -1));

        kursi32.setBackground(new java.awt.Color(48, 57, 82));
        kursi32.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi32.setForeground(new java.awt.Color(48, 57, 82));
        kursi32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi32.setText("kursi1");
        jPanel1.add(kursi32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 40, -1));

        kursi31.setBackground(new java.awt.Color(48, 57, 82));
        kursi31.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi31.setForeground(new java.awt.Color(48, 57, 82));
        kursi31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi31.setText("kursi1");
        jPanel1.add(kursi31, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 40, -1));

        kursi30.setBackground(new java.awt.Color(48, 57, 82));
        kursi30.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi30.setForeground(new java.awt.Color(48, 57, 82));
        kursi30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi30.setText("kursi1");
        jPanel1.add(kursi30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 40, -1));

        kursi29.setBackground(new java.awt.Color(48, 57, 82));
        kursi29.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi29.setForeground(new java.awt.Color(48, 57, 82));
        kursi29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi29.setText("kursi1");
        jPanel1.add(kursi29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 40, -1));

        kursi28.setBackground(new java.awt.Color(48, 57, 82));
        kursi28.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi28.setForeground(new java.awt.Color(48, 57, 82));
        kursi28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi28.setText("kursi1");
        jPanel1.add(kursi28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 40, -1));

        kursi27.setBackground(new java.awt.Color(48, 57, 82));
        kursi27.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi27.setForeground(new java.awt.Color(48, 57, 82));
        kursi27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi27.setText("kursi1");
        jPanel1.add(kursi27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 40, -1));

        kursi26.setBackground(new java.awt.Color(48, 57, 82));
        kursi26.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi26.setForeground(new java.awt.Color(48, 57, 82));
        kursi26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi26.setText("kursi1");
        jPanel1.add(kursi26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 40, -1));

        kursi25.setBackground(new java.awt.Color(48, 57, 82));
        kursi25.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi25.setForeground(new java.awt.Color(48, 57, 82));
        kursi25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi25.setText("kursi1");
        jPanel1.add(kursi25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 40, -1));

        kursi24.setBackground(new java.awt.Color(48, 57, 82));
        kursi24.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi24.setForeground(new java.awt.Color(48, 57, 82));
        kursi24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi24.setText("kursi1");
        jPanel1.add(kursi24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 40, -1));

        kursi23.setBackground(new java.awt.Color(48, 57, 82));
        kursi23.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi23.setForeground(new java.awt.Color(48, 57, 82));
        kursi23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi23.setText("kursi1");
        jPanel1.add(kursi23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 40, -1));

        kursi21.setBackground(new java.awt.Color(48, 57, 82));
        kursi21.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi21.setForeground(new java.awt.Color(48, 57, 82));
        kursi21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi21.setText("kursi1");
        jPanel1.add(kursi21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 40, -1));

        kursi22.setBackground(new java.awt.Color(48, 57, 82));
        kursi22.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi22.setForeground(new java.awt.Color(48, 57, 82));
        kursi22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi22.setText("kursi1");
        jPanel1.add(kursi22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 40, -1));

        kursi20.setBackground(new java.awt.Color(48, 57, 82));
        kursi20.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi20.setForeground(new java.awt.Color(48, 57, 82));
        kursi20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi20.setText("kursi1");
        jPanel1.add(kursi20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 40, -1));

        kursi19.setBackground(new java.awt.Color(48, 57, 82));
        kursi19.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi19.setForeground(new java.awt.Color(48, 57, 82));
        kursi19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi19.setText("kursi1");
        jPanel1.add(kursi19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 40, -1));

        kursi18.setBackground(new java.awt.Color(48, 57, 82));
        kursi18.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi18.setForeground(new java.awt.Color(48, 57, 82));
        kursi18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi18.setText("kursi1");
        jPanel1.add(kursi18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 40, -1));

        kursi17.setBackground(new java.awt.Color(48, 57, 82));
        kursi17.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi17.setForeground(new java.awt.Color(48, 57, 82));
        kursi17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi17.setText("kursi1");
        jPanel1.add(kursi17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 40, -1));

        kursi16.setBackground(new java.awt.Color(48, 57, 82));
        kursi16.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi16.setForeground(new java.awt.Color(48, 57, 82));
        kursi16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi16.setText("kursi1");
        jPanel1.add(kursi16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 40, -1));

        kursi15.setBackground(new java.awt.Color(48, 57, 82));
        kursi15.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi15.setForeground(new java.awt.Color(48, 57, 82));
        kursi15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi15.setText("kursi1");
        jPanel1.add(kursi15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 40, -1));

        kursi14.setBackground(new java.awt.Color(48, 57, 82));
        kursi14.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi14.setForeground(new java.awt.Color(48, 57, 82));
        kursi14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi14.setText("kursi1");
        jPanel1.add(kursi14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 40, -1));

        kursi13.setBackground(new java.awt.Color(48, 57, 82));
        kursi13.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi13.setForeground(new java.awt.Color(48, 57, 82));
        kursi13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi13.setText("kursi1");
        jPanel1.add(kursi13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 40, -1));

        kursi12.setBackground(new java.awt.Color(48, 57, 82));
        kursi12.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi12.setForeground(new java.awt.Color(48, 57, 82));
        kursi12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi12.setText("kursi1");
        jPanel1.add(kursi12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 40, -1));

        kursi11.setBackground(new java.awt.Color(48, 57, 82));
        kursi11.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi11.setForeground(new java.awt.Color(48, 57, 82));
        kursi11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi11.setText("kursi1");
        jPanel1.add(kursi11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 40, -1));

        kursi10.setBackground(new java.awt.Color(48, 57, 82));
        kursi10.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi10.setForeground(new java.awt.Color(48, 57, 82));
        kursi10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi10.setText("kursi1");
        jPanel1.add(kursi10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 40, -1));

        kursi9.setBackground(new java.awt.Color(48, 57, 82));
        kursi9.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi9.setForeground(new java.awt.Color(48, 57, 82));
        kursi9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi9.setText("kursi1");
        jPanel1.add(kursi9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 40, -1));

        kursi8.setBackground(new java.awt.Color(48, 57, 82));
        kursi8.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi8.setForeground(new java.awt.Color(48, 57, 82));
        kursi8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi8.setText("kursi1");
        jPanel1.add(kursi8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 40, -1));

        kursi7.setBackground(new java.awt.Color(48, 57, 82));
        kursi7.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi7.setForeground(new java.awt.Color(48, 57, 82));
        kursi7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi7.setText("kursi1");
        jPanel1.add(kursi7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 40, -1));

        kursi6.setBackground(new java.awt.Color(48, 57, 82));
        kursi6.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi6.setForeground(new java.awt.Color(48, 57, 82));
        kursi6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_selected.png"))); // NOI18N
        kursi6.setText("kursi1");
        jPanel1.add(kursi6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 40, -1));

        kursi5.setBackground(new java.awt.Color(48, 57, 82));
        kursi5.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi5.setForeground(new java.awt.Color(48, 57, 82));
        kursi5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi5.setText("kursi1");
        jPanel1.add(kursi5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 40, -1));

        kursi4.setBackground(new java.awt.Color(48, 57, 82));
        kursi4.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi4.setForeground(new java.awt.Color(48, 57, 82));
        kursi4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi4.setText("kursi1");
        jPanel1.add(kursi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 40, -1));

        kursi3.setBackground(new java.awt.Color(48, 57, 82));
        kursi3.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi3.setForeground(new java.awt.Color(48, 57, 82));
        kursi3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi3.setText("kursi1");
        jPanel1.add(kursi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 40, -1));

        kursi2.setBackground(new java.awt.Color(48, 57, 82));
        kursi2.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi2.setForeground(new java.awt.Color(48, 57, 82));
        kursi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        kursi2.setText("kursi1");
        jPanel1.add(kursi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 40, -1));

        kursi1.setBackground(new java.awt.Color(48, 57, 82));
        kursi1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        kursi1.setForeground(new java.awt.Color(48, 57, 82));
        kursi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_not_available.png"))); // NOI18N
        kursi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kursi1MouseClicked(evt);
            }
        });
        jPanel1.add(kursi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, -1));

        no_2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        no_2.setForeground(new java.awt.Color(255, 255, 255));
        no_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_2.setText("2");
        jPanel1.add(no_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 30, 40));

        no_3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        no_3.setForeground(new java.awt.Color(255, 255, 255));
        no_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_3.setText("3");
        jPanel1.add(no_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 30, 40));

        no_4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        no_4.setForeground(new java.awt.Color(255, 255, 255));
        no_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_4.setText("4");
        jPanel1.add(no_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 30, 40));

        no_5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        no_5.setForeground(new java.awt.Color(255, 255, 255));
        no_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_5.setText("5");
        jPanel1.add(no_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 30, 40));

        no_6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        no_6.setForeground(new java.awt.Color(255, 255, 255));
        no_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_6.setText("6");
        jPanel1.add(no_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 30, 40));

        no_7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        no_7.setForeground(new java.awt.Color(255, 255, 255));
        no_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_7.setText("7");
        jPanel1.add(no_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 30, 40));

        no_8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        no_8.setForeground(new java.awt.Color(255, 255, 255));
        no_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_8.setText("8");
        jPanel1.add(no_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 30, 40));

        no_9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        no_9.setForeground(new java.awt.Color(255, 255, 255));
        no_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_9.setText("9");
        jPanel1.add(no_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 30, 40));

        no_10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        no_10.setForeground(new java.awt.Color(255, 255, 255));
        no_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_10.setText("10");
        jPanel1.add(no_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 30, 40));

        no_1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        no_1.setForeground(new java.awt.Color(255, 255, 255));
        no_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_1.setText("1");
        jPanel1.add(no_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 29, 30, 40));

        A.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        A.setForeground(new java.awt.Color(255, 255, 255));
        A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A.setText("A");
        jPanel1.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, -1));

        B.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        B.setForeground(new java.awt.Color(255, 255, 255));
        B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B.setText("B");
        jPanel1.add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 40, -1));

        C.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        C.setForeground(new java.awt.Color(255, 255, 255));
        C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C.setText("C");
        jPanel1.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, -1));

        D.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        D.setForeground(new java.awt.Color(255, 255, 255));
        D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D.setText("D");
        jPanel1.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 40, -1));

        Panel_List_Penerbangan.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 300, 530));

        ex_selected.setBackground(new java.awt.Color(48, 57, 82));
        ex_selected.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        ex_selected.setForeground(new java.awt.Color(48, 57, 82));
        ex_selected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_selected.png"))); // NOI18N
        ex_selected.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ex_selectedMouseClicked(evt);
            }
        });
        Panel_List_Penerbangan.add(ex_selected, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 40, -1));

        ex_available.setBackground(new java.awt.Color(48, 57, 82));
        ex_available.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        ex_available.setForeground(new java.awt.Color(48, 57, 82));
        ex_available.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_available.png"))); // NOI18N
        ex_available.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ex_availableMouseClicked(evt);
            }
        });
        Panel_List_Penerbangan.add(ex_available, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 40, 40));

        ex_not_available2.setBackground(new java.awt.Color(48, 57, 82));
        ex_not_available2.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        ex_not_available2.setForeground(new java.awt.Color(48, 57, 82));
        ex_not_available2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/seat/seatBox_not_available.png"))); // NOI18N
        ex_not_available2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ex_not_available2MouseClicked(evt);
            }
        });
        Panel_List_Penerbangan.add(ex_not_available2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 40, -1));

        jLabel13.setBackground(new java.awt.Color(48, 57, 82));
        jLabel13.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(48, 57, 82));
        jLabel13.setText("Pilih Kursi");
        Panel_List_Penerbangan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 3, 110, 30));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(48, 57, 82));
        jLabel14.setText("Tersedia");
        Panel_List_Penerbangan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 130, 40));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(48, 57, 82));
        jLabel15.setText("Tidak Tersedia");
        Panel_List_Penerbangan.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 130, 40));

        getContentPane().add(Panel_List_Penerbangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 580));

        Background.setBackground(new java.awt.Color(48, 57, 82));
        Background.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int xMouse, yMouse;
    private void moveableFrame1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveableFrame1MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse ,y-yMouse);
    }//GEN-LAST:event_moveableFrame1MouseDragged

    private void moveableFrame1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveableFrame1MousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_moveableFrame1MousePressed

    private void btnSimpanDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanDataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanDataMouseClicked

    private void btnSimpanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanDataActionPerformed

    private void btnBack2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack2MouseClicked

    }//GEN-LAST:event_btnBack2MouseClicked

    private void kursi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kursi1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kursi1MouseClicked

    private void ex_selectedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ex_selectedMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ex_selectedMouseClicked

    private void ex_availableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ex_availableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ex_availableMouseClicked

    private void ex_not_available2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ex_not_available2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ex_not_available2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Panel_User_pilih_Kursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Panel_User_pilih_Kursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Panel_User_pilih_Kursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Panel_User_pilih_Kursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
     
        
        System.out.println("test");
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Panel_User_pilih_Kursi().setVisible(true);
                
            }
        });
    }

    public JButton getBtnSimpanData() {
        return btnSimpanData;
    }

    public void setBtnSimpanData(JButton btnSimpanData) {
        this.btnSimpanData = btnSimpanData;
    }

    
    public JLabel getBtnBack2() {
        return btnBack2;
    }

    public void setBtnBack2(JLabel btnBack2) {
        this.btnBack2 = btnBack2;
    }

    public void addListener(MouseListener mouseListener) {
        btnSimpanData.addMouseListener(mouseListener);
        btnBack2.addMouseListener(mouseListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel C;
    private javax.swing.JLabel D;
    private javax.swing.JPanel Panel_List_Penerbangan;
    private javax.swing.JLabel btnBack2;
    private javax.swing.JButton btnSimpanData;
    private javax.swing.JLabel ex_available;
    private javax.swing.JLabel ex_not_available2;
    private javax.swing.JLabel ex_selected;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kursi1;
    private javax.swing.JLabel kursi10;
    private javax.swing.JLabel kursi11;
    private javax.swing.JLabel kursi12;
    private javax.swing.JLabel kursi13;
    private javax.swing.JLabel kursi14;
    private javax.swing.JLabel kursi15;
    private javax.swing.JLabel kursi16;
    private javax.swing.JLabel kursi17;
    private javax.swing.JLabel kursi18;
    private javax.swing.JLabel kursi19;
    private javax.swing.JLabel kursi2;
    private javax.swing.JLabel kursi20;
    private javax.swing.JLabel kursi21;
    private javax.swing.JLabel kursi22;
    private javax.swing.JLabel kursi23;
    private javax.swing.JLabel kursi24;
    private javax.swing.JLabel kursi25;
    private javax.swing.JLabel kursi26;
    private javax.swing.JLabel kursi27;
    private javax.swing.JLabel kursi28;
    private javax.swing.JLabel kursi29;
    private javax.swing.JLabel kursi3;
    private javax.swing.JLabel kursi30;
    private javax.swing.JLabel kursi31;
    private javax.swing.JLabel kursi32;
    private javax.swing.JLabel kursi33;
    private javax.swing.JLabel kursi34;
    private javax.swing.JLabel kursi35;
    private javax.swing.JLabel kursi36;
    private javax.swing.JLabel kursi37;
    private javax.swing.JLabel kursi38;
    private javax.swing.JLabel kursi39;
    private javax.swing.JLabel kursi4;
    private javax.swing.JLabel kursi40;
    private javax.swing.JLabel kursi5;
    private javax.swing.JLabel kursi6;
    private javax.swing.JLabel kursi7;
    private javax.swing.JLabel kursi8;
    private javax.swing.JLabel kursi9;
    private javax.swing.JPanel moveableFrame1;
    private javax.swing.JLabel no_1;
    private javax.swing.JLabel no_10;
    private javax.swing.JLabel no_2;
    private javax.swing.JLabel no_3;
    private javax.swing.JLabel no_4;
    private javax.swing.JLabel no_5;
    private javax.swing.JLabel no_6;
    private javax.swing.JLabel no_7;
    private javax.swing.JLabel no_8;
    private javax.swing.JLabel no_9;
    // End of variables declaration//GEN-END:variables
       
}
