/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user;

import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class View_Panel_User_ListPenerbangan extends javax.swing.JFrame {

    /**
     * Creates new form View_Panel_User_ListPenerbangan
     */
    public View_Panel_User_ListPenerbangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_List_Penerbangan = new javax.swing.JPanel();
        moveableFrame1 = new javax.swing.JPanel();
        borderList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_pesawat = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtKelas = new javax.swing.JTextField();
        txtKodePesawat = new javax.swing.JTextField();
        btnPilihPenerbangan = new javax.swing.JButton();
        txtNamaPesawat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(48, 57, 82));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_List_Penerbangan.setBackground(new java.awt.Color(255, 255, 255));
        Panel_List_Penerbangan.setForeground(new java.awt.Color(255, 255, 255));
        Panel_List_Penerbangan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        moveableFrame1.setOpaque(false);
        moveableFrame1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveableFrame1MouseDragged(evt);
            }
        });
        moveableFrame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveableFrame1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout moveableFrame1Layout = new javax.swing.GroupLayout(moveableFrame1);
        moveableFrame1.setLayout(moveableFrame1Layout);
        moveableFrame1Layout.setHorizontalGroup(
            moveableFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        moveableFrame1Layout.setVerticalGroup(
            moveableFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel_List_Penerbangan.add(moveableFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 40));

        borderList.setBackground(new java.awt.Color(48, 57, 82));
        borderList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(48, 57, 82));

        list_pesawat.setBackground(new java.awt.Color(48, 57, 82));
        list_pesawat.setForeground(new java.awt.Color(255, 255, 255));
        list_pesawat.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_pesawatValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_pesawat);

        borderList.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 420, 280));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("List Pesawat");
        borderList.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        Panel_List_Penerbangan.add(borderList, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 460, 350));

        jLabel11.setBackground(new java.awt.Color(48, 57, 82));
        jLabel11.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(48, 57, 82));
        jLabel11.setText("Penerbangan yang tersedia");
        Panel_List_Penerbangan.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jLabel6.setBackground(new java.awt.Color(48, 57, 82));
        jLabel6.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(48, 57, 82));
        jLabel6.setText("Kelas  :");
        Panel_List_Penerbangan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        jLabel7.setBackground(new java.awt.Color(48, 57, 82));
        jLabel7.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(48, 57, 82));
        jLabel7.setText("Detail Pesawat");
        Panel_List_Penerbangan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, -1));

        jLabel8.setBackground(new java.awt.Color(48, 57, 82));
        jLabel8.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(48, 57, 82));
        jLabel8.setText("Kode   :");
        Panel_List_Penerbangan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        txtKelas.setEnabled(false);
        txtKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKelasActionPerformed(evt);
            }
        });
        Panel_List_Penerbangan.add(txtKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 160, 30));

        txtKodePesawat.setEnabled(false);
        txtKodePesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodePesawatActionPerformed(evt);
            }
        });
        Panel_List_Penerbangan.add(txtKodePesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 160, 30));

        btnPilihPenerbangan.setBackground(new java.awt.Color(47, 54, 64));
        btnPilihPenerbangan.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        btnPilihPenerbangan.setForeground(new java.awt.Color(255, 255, 255));
        btnPilihPenerbangan.setText("Pilih Penerbangan");
        btnPilihPenerbangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPilihPenerbanganMouseClicked(evt);
            }
        });
        btnPilihPenerbangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihPenerbanganActionPerformed(evt);
            }
        });
        Panel_List_Penerbangan.add(btnPilihPenerbangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 180, 50));

        txtNamaPesawat.setEnabled(false);
        txtNamaPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPesawatActionPerformed(evt);
            }
        });
        Panel_List_Penerbangan.add(txtNamaPesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 160, 30));

        jLabel9.setBackground(new java.awt.Color(48, 57, 82));
        jLabel9.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(48, 57, 82));
        jLabel9.setText("Nama  :");
        Panel_List_Penerbangan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        txtHarga.setEnabled(false);
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        Panel_List_Penerbangan.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 160, 30));

        jLabel10.setBackground(new java.awt.Color(48, 57, 82));
        jLabel10.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(48, 57, 82));
        jLabel10.setText("Harga  :");
        Panel_List_Penerbangan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        getContentPane().add(Panel_List_Penerbangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 580));

        Background.setBackground(new java.awt.Color(48, 57, 82));
        Background.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int xMouse, yMouse;
    private void moveableFrame1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveableFrame1MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse ,y-yMouse);
    }//GEN-LAST:event_moveableFrame1MouseDragged

    private void moveableFrame1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveableFrame1MousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_moveableFrame1MousePressed

    private void btnPilihPenerbanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihPenerbanganMouseClicked
        // TODO add your handling code here:

        //        this.setVisible(false);
    }//GEN-LAST:event_btnPilihPenerbanganMouseClicked

    private void btnPilihPenerbanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihPenerbanganActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btnPilihPenerbanganActionPerformed

    private void txtKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelasActionPerformed

    private void txtKodePesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodePesawatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodePesawatActionPerformed

    private void list_pesawatValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_pesawatValueChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_list_pesawatValueChanged

    private void txtNamaPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPesawatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPesawatActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Panel_User_ListPenerbangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Panel_User_ListPenerbangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Panel_User_ListPenerbangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Panel_User_ListPenerbangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Panel_User_ListPenerbangan().setVisible(true);
            }
        });
    }

    public JButton getBtnPilihPenerbangan() {
        return btnPilihPenerbangan;
    }

    public void setBtnPilihPenerbangan(JButton btnPilihPenerbangan) {
        this.btnPilihPenerbangan = btnPilihPenerbangan;
    }

    public JList<String> getList_pesawat() {
        return list_pesawat;
    }

    public void setList_pesawat(JList<String> list_pesawat) {
        this.list_pesawat = list_pesawat;
    }

    public JTextField getTxtHarga() {
        return txtHarga;
    }

    public void setTxtHarga(JTextField txtHarga) {
        this.txtHarga = txtHarga;
    }

    public JTextField getTxtKelas() {
        return txtKelas;
    }

    public void setTxtKelas(JTextField txtKelas) {
        this.txtKelas = txtKelas;
    }

    public JTextField getTxtKodePesawat() {
        return txtKodePesawat;
    }

    public void setTxtKodePesawat(JTextField txtKodePesawat) {
        this.txtKodePesawat = txtKodePesawat;
    }

    public JTextField getTxtNamaPesawat() {
        return txtNamaPesawat;
    }

    public void setTxtNamaPesawat(JTextField txtNamaPesawat) {
        this.txtNamaPesawat = txtNamaPesawat;
    }

   
    public void addListener(MouseListener mouseListener) {
        btnPilihPenerbangan.addMouseListener(mouseListener);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Panel_List_Penerbangan;
    private javax.swing.JPanel borderList;
    private javax.swing.JButton btnPilihPenerbangan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_pesawat;
    private javax.swing.JPanel moveableFrame1;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtKodePesawat;
    private javax.swing.JTextField txtNamaPesawat;
    // End of variables declaration//GEN-END:variables
}
